config/routes.rb
Rails.application.routes.draw do  
  resources :wines, only: [:index, :new, :create] do 
    resources :reviews, only: [:index, :new]
  end

  resources :reviews, only: :create
  get '/wines/red', to: 'wines#red' 
  get '/wines/white', to: 'wines#white'
  get '/wines/sparkling', to: 'wines#sparkling'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/winecellar', to: 'users#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :wine
    #validates :rating, inclusion: { in: [1,2,3,4,5]}
    validates_presence_of :review
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :reviews
    has_many :wines, through: :reviews
    validates_presence_of :name, :password
    validates_uniqueness_of :name
end

app/models/wine.rb
class Wine < ApplicationRecord
    has_many :reviews
    has_many :users, through: :reviews
    validates_presence_of :name

    scope :red, -> { where(grape_variety: 'Red') }
    scope :white, -> { where(grape_variety: 'White') }
    scope :sparkling, -> { where(grape_variety: 'Sparkling')} 
  
    def self.search(search)
        where("name LIKE ?", "%#{search.strip}%") 
        #SQL operator that finds any values that are similar to search input
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

      def current_user 
        User.find_by(id: session[:user_id]) 
      end

      def require_login
        redirect_to wines_path unless logged_in?
      end

      def logged_in?
        !!current_user
      end

      def log_in(user)
        session[:user_id] = user.id
      end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :require_login
    before_action :get_wine, only: [ :index, :new]
    def index
        #get_wine
        wine_exists
        current_user
    end

    def new 
        #get_wine
        wine_exists
        @review = Review.new
    end

    def create 
       @wine = Wine.find_by(id: params[:review][:wine_id])
       @review = current_user.reviews.build(review_params)
        if @review.save 
            redirect_to wine_reviews_path(@review.wine)
        else
            render :new
        end
    end
 
    private 

    def get_wine
        @wine ||= Wine.find_by(id: params[:wine_id])
    end

    def wine_exists
        redirect_to wines_path if !@wine
    end

    def review_params
        params.require(:review).permit(:review, :wine_id, :rating)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new 
    end

    def create
        if request.env['omniauth.auth']
            @user = User.find_by(github_uid: request.env['omniauth.auth']['uid'])
            if @user.nil?
                @user = User.create(name: request.env['omniauth.auth']['info']['nickname'], github_uid: request.env['omniauth.auth']['uid'], password: 'github')
            end
            log_in(@user)
            redirect_to wines_path
        else
            @user = User.find_by(name: params[:name])
            if !@user 
                @error = 'Account not found.'
                render :new 
            elsif !@user.authenticate(params[:password])
                @error = "Username or password incorrect. Please try again."
                render :new
            else
                log_in(@user)
                redirect_to wines_path
            end
         end
     end

    def destroy
        session.clear
        redirect_to wines_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


# GET /register - new user action
    def new
      @user = User.new
    end
# Post /users - create the user action
    def create
        @user = User.new(user_params)
        if @user.save
            log_in(@user)
            redirect_to wine_reviews_path
        else
            render :new 
        end
    end


    def show 
        @wines = current_user.wines.build
        render :show
    end
    private 

    def user_params
        params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
    before_action :logged_in?
    def index 
        @wines = Wine.all
        #params[:search] is taken in as the argument implemented through the wines index page
        if params[:search]
            @wines = Wine.search(params[:search]).order("year DESC")
          else
            @wines = Wine.all.order('year DESC')
          end
        end
    end

    def new 
        # @wine = Wine.find(params[:id])
        # @review = Review.new
        @wine = Wine.new
    end 

    def create
        @wine = Wine.new(wine_params)
        
        if @wine.save
            redirect_to wines_path(@wine)
        else
            render :new
        end
    end

    def red 
        @wines = Wine.red 
        render :index
    end

    def white 
        @wines = Wine.white
        render :index
    end

    def sparkling 
        @wines = Wine.sparkling
        render :index
    end


    private 
    

    def wine_params
        params.require(:wine).permit(:name, :grape_variety, :country_of_origin, :year)
    end 



app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user 
        User.find_by(id: session[:user_id])
      end
      
    def logged_in?
        !!current_user
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/layouts/_navbar.html.erb
<div class="header">
    <div class="title">Wines</div>
    <% if current_user %>
        <div class="name">
            <i>Welcome, <%= current_user.name %></i>
        </div>
    <% end %> 
    <div class="nav">
    <div><a href='/wines'>Wines</a></div>
    <% if logged_in? %>
        <div><a href='/winecellar'>Wine Cellar</a></div>
        <div><a href='/logout'>Log Out</a></div>
    <% else %> 
        <div><a href='/signup'>Sign Up</a></div>
        <div><a href='/login'>Log In</a></div>
    <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WineCellar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <navbar>
      <%= render 'layouts/navbar' %>
    </navbar>
    <main class="wrapper">
      <%= yield %>
      </main>
  </body>
</html>

app/views/reviews/index.html.erb
<h2> Reviews of <i><%= @wine.name %></i></h2>

<b><%= link_to "Add New Review".html_safe, new_wine_review_path(@wine) %> </b>
<% @wine.reviews.each do |review| %>
    
    <p><%= review.review %></p>
    <p><%= review.rating %> out of 5</p>
    <p>Review on: <%= review.created_at.strftime("%Y-%m-%d") %></p>
    <hr>

<% end %>







app/views/reviews/new.html.erb

<h2> Add a Review for <i><%= @wine.name %></i></h2>

<%= render partial: '/errors', locals: { record: @review } %>

<%= form_for @review do |f| %>
    <%= f.label :review %>
    <div><%= f.text_area :review %></div>
    
    
    <%= f.label :rating %> 
    <div><%= f.text_area :rating %>

    <%= f.hidden_field :wine_id, value: @wine.id %>
    <div><%= f.submit "Add Review" %></div>
<% end %>

app/views/users/new.html.erb
<h1> Register to Rate and Review Wine </h1>

<%= render partial: '/errors', locals: { record: @user } %>

<%= form_for @user, url: signup_path do |f| %>
    <%= f.label :name %>
    <div><%= f.text_field :name %><div><br />
    <%= f.label :password %>
    <div><%= f.password_field :password %></div>
    <% f.label :confirm_password %>
    <div><%= f.password_field :password_confirmation%></div>
    <%= f.submit "Join" %>
<% end %>

app/views/users/show.html.erb
<h2> Your Wine Cellar </h2>

<p><% current_user.reviews.each do |review| %></p>
        <p><%= review.wine.name  %></p>
            <%= review.review %>
    <%end%>
    <hr>

app/views/wines/index.html.erb
<h2> Wines </h2>

<u><%= link_to "Filter by Red Wines", wines_red_path %></u>
<u><%= link_to "Filter by White Wines", wines_white_path %></u>
<u><%= link_to "Filter by Sparkling Wines", wines_sparkling_path %></u>
<u><%= link_to "See All Wines", wines_path %></u>

<%= form_tag(wines_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Wines" %>
    <%= submit_tag "Search", :name => nil%>
<% end %>


<% @wines.each do |wine| %>
    <h3><%= link_to wine.name, wine_reviews_path(wine)%></h3>
   
    <p>Year: <%= wine.year %></p>
    <p>Grape Variety: <%= wine.grape_variety %></p>
    <p>Country of Origin: <%= wine.country_of_origin %></p>

<% end %>


app/views/wines/new.html.erb
<h2> Add a Wine </h2>

<%= render partial: '/errors', locals: { record: @wine } %>

<%= form_for @wine do |f| %>
    <%= f.label :name %>
    <div><%= f.text_field :name %></div>
    <p><%= f.label :year %></p>
    <div><%= f.text_field :year %></div>
    <p><%= f.label :grape_variety %></p>
    <div><%= f.text_field :grape_variety %></div>
    <p><%= f.label :country_of_origin %></p>
    <div><%= f.text_field :country_of_origin %></div>
  
    

    <%= f.submit "Add Wine" %>
<% end %>
